/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'USB_FS.Debug+STM32F407VETx' 
 * Target:  'Debug+STM32F407VETx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* Keil::CMSIS Driver:USB Device:Full-speed@2.23 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
/* Keil::Device:STM32Cube Framework:Classic@1.8.1 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:Common@1.8.1 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.8.1 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:GPIO@1.8.1 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PCD@1.8.1 */
#define RTE_DEVICE_HAL_PCD
/* Keil::Device:STM32Cube HAL:RCC@1.8.1 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:Startup@2.6.3 */
#define RTE_DEVICE_STARTUP_STM32F4XX    /* Device Startup for STM32F4 */


#endif /* RTE_COMPONENTS_H */
